### ISSUE TITLE
No module named exceptions

### ISSUE THREAD

**Issue by OctoNezd** [kanzure/python-vba-wrapper#6]
`nezd:~/workspace $ python3 bot.py 
Traceback (most recent call last):
  File "bot.py", line 1, in <module>
    import vba_wrapper
  File "/usr/local/lib/python3.4/dist-packages/vba_wrapper/__init__.py", line 16, in <module>
    import exceptions
ImportError: No module named 'exceptions'
nezd:~/workspace $`

**Comment by kanzure** [comment]
what is `bot.py`?

https://github.com/kanzure/python-vba-wrapper/blob/master/vba_wrapper/exceptions.py

**Comment by OctoNezd** [comment]
bot.py is my code

**Comment by OctoNezd** [comment]
Maybe it cause that there were a library named exceptions in python2, but im running on python3?

**Comment by kanzure** [comment]
For your purposes you would probably need to have:

```
import .exceptions
import .core
```

instead of:

```
import exceptions
import core
```

in `vba_wrapper/__init__.py`. Could you try making that change and letting me know?

**Comment by OctoNezd** [comment]
I using version from pip. Will install from git and test again

**Comment by OctoNezd** [comment]
Now it have other error:
'
nezd:~/workspace $ python3 bot.py 
Traceback (most recent call last):
  File "bot.py", line 1, in <module>
    import vba_wrapper
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2222, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 2164, in _find_spec
  File "<frozen importlib._bootstrap>", line 1940, in find_spec
  File "<frozen importlib._bootstrap>", line 1916, in _get_spec
  File "<frozen importlib._bootstrap>", line 1897, in _legacy_get_spec
  File "<frozen importlib._bootstrap>", line 863, in spec_from_loader
  File "<frozen importlib._bootstrap>", line 904, in spec_from_file_location
  File "/usr/local/lib/python3.4/dist-packages/vba_wrapper-0.0.2-py3.4.egg/vba_wrapper/__init__.py", line 15
    import .exceptions
           ^
SyntaxError: invalid syntax
'

**Comment by OctoNezd** [comment]
If i comment import exceptions, it cant import core

**Comment by kanzure** [comment]
You can remove all three of the offending lines (the two import statements and the variable assignment at the end of the file). I have not tested this library with python3 yet.

By the way, this library requires https://github.com/kanzure/vba-linux .... another bag of thorns.

**Comment by OctoNezd** [comment]
File "bot.py", line 3, in <module>
    vba = vba_wrapper.VBA("/home/ubuntu/workspace/Pokemon - Red Version (USA, Europe).gb")
AttributeError: 'module' object has no attribute 'VBA'

**Comment by OctoNezd** [comment]
If i replace VBA to core:
Traceback (most recent call last):
  File "bot.py", line 3, in <module>
    vba = vba_wrapper.core("/home/ubuntu/workspace/Pokemon - Red Version (USA, Europe).gb")
AttributeError: 'module' object has no attribute 'core'

**Comment by OctoNezd** [comment]
So, i make some things and now it imports libs, i will make a pull req with fix soon

**Comment by OctoNezd** [comment]
Waiting for merge
